program: scripts/training.py
name: katelyn-v1-images-escnn-equiv
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  dataset_name:
    value: ImageFoldersDataModule
  d_hparams:
    parameters:
      batch_size:
        value: 64
      test_batch_size:
        value: 128
      train_dir:
        value: /vast/home/karella/rotation-invariant-neural-networks/hippy2d/data/v1-images/train
      valid_dir:
        value: /vast/home/karella/rotation-invariant-neural-networks/hippy2d/data/v1-images/val
      test_dir:
        value: /vast/home/karella/rotation-invariant-neural-networks/hippy2d/data/v1-images/test
      target_size:
        value: 224
      aug_gray_scale:
        value: true
      to_complex:
        value: false
      aug_flips:
        value: true
      train_data_fraction:
        values: [0.5, 1]
  early_stopping:
    value: 30
  epochs:
    value: 100
  lr_name:
    value: MultiStepLR
  lr_hparams:
    parameters:
      gamma:
        value: 0.1
      milestones:
        value: [30, 50, 70]
  model_name:
    value: E2Cnn
  m_param:
    parameters:
      in_channels:
        value: 1
      input_size:
        value: 224
      max_order:
        value: 3
      stem_channels:
        value: 16
      channels:
        value: [16, 32, 40]
      block_type:
        value: GatedBlock
      trivial_pooling_type:
        value: PointwiseMaxPool
  optimizer_hparams:
    parameters:
      lr:
        value: 0.001
      weight_decay:
        value: 0.05
  optimizer_name:
    value: AdamW
  label_smoothing:
    value: 0.1
  run_name:
    value: e2cnn-katelyn-v1-images-sweep
  seed:
    values: [42, 7, 74]
