d_hparams:
  test_batch_size: 8
  batch_size: 32
  normalize: true
  aug_rotation: true
dataset_name: ColorectalHistology
early_stopping: 30
epochs: 100
lr_hparams:
  gamma: 0.1
  milestones:
  - 50
  - 100
  - 125
lr_name: MultiStepLR
model_name: Resnet 
m_param:
  in_channels: 3
  input_size: 150
  norm: batch
  kernels_size: [15, 11, 11, 11]
  layer: "LearnableCesa"
optimizer_hparams:
  lr: 0.0001525
optimizer_name: AdamW
label_smoothing: 0.1
seed: 390
run_name: resnet-testing
debug: true