d_hparams:
  test_batch_size: 64
  batch_size: 64
  normalize: True
  use_circ_mask: True
dataset_name: ColorectalHistology
early_stopping: 30
epochs: 100
lr_hparams:
  gamma: 0.1
  milestones:
  - 30
  - 50
  - 70
lr_name: MultiStepLR
model_name: Resnet 
m_param:
  in_channels: 3
  input_size: 150
  norm: batch
  kernels_size: [11, 11, 11]
  layers: [1, 2, 2]
  channels: [16, 20, 26]
  block_types: ["TimmBasicBlock", "TimmBasicBlock", "TimmBasicBlock"]
  layer: "LearnableCesa"
  drop_rate: 0.1
  channels_masking: True
optimizer_hparams:
  lr: 0.001525
  weight_decay: 0.05
optimizer_name: AdamW
run_name: learnable-cesa-norm-magnitude
seed: 42
label_smoothing: 0.1
