program: scripts/training.py
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  dataset_name:
    value: ColorectalHistology
  d_hparams:
    parameters:
      batch_size:
        value: 64
      test_batch_size:
        value: 64
      data_dir:
        value: data
      target_size:
        value: 96
      normalize:
        value: false
      use_circ_mask: 
        value: true
  early_stopping:
    value: 25
  epochs:
    value: 150
  lr_name:
    value: MultiStepLR
  lr_hparams:
    parameters:
      gamma:
        value: 0.1
      milestones:
        value: [20, 40, 60]
  m_param:
    parameters:
      in_channels:
        value: 3
      num_classes:
        value: 10
      input_size:
        value: 96
      disable_act1:
        value: true
      norm1_layer:
        value: none
      norm2_layer:
        value: batch
      kernels_size:
        value: [11, 11, 11]
      layers:
        value: [1, 2, 2]
      channels:
        value: [16, 20, 26]
      block_types:
        value: ["MBConvBlock", "MBConvBlock", "MBConvBlock"]
      layer:
        value: "LearnableCesaMagRealVarFunc"
      default_layer_kwargs: 
        parameters:
          norm_per_inv_type: 
            values: ["layer", "batch", "none"]
          magnitude_only: 
            value: true
      drop_rate:
        value: 0.1
      channels_masking:
        value: true
  model_name:
    value: MBPrototype
  optimizer_hparams:
    parameters:
      lr:
        value: 0.001
  optimizer_name:
    value: AdamW
  label_smoothing:
    value: 0.1
  run_name:
    value: hist-circ-mbconv-mag-func-search-in-norm
  seed:
    values: [42, 7, 123]
