
program: scripts/training.py
name: learnablecesa-rotmnist-mag-func-search-sep-norm
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  dataset_name:
    value: RotMnist
  d_hparams:
    parameters:
      batch_size:
        value: 32
      test_batch_size:
        value: 128
      data_dir:
        value: data
      upscale_size:
        value: 64
  early_stopping:
    value: 15
  epochs:
    value: 100
  lr_name:
    value: MultiStepLR
  lr_hparams:
    parameters:
      gamma:
        value: 0.1
      milestones:
        value: [30, 50, 70]
  m_param:
    parameters:
      in_channels:
        value: 1
      num_classes:
        value: 10 
      disable_act1:
        value: true
      norm1_layer:
        value: none
      norm2_layer:
        value: batch
      kernels_size:
        value: [11, 11, 11]
      layers:
        value: [1, 2, 2]
      channels:
        value: [16, 20, 26]
      block_types:
        value: ["MBConvBlock", "MBConvBlock", "MBConvBlock"]
      layer:
        value: "LearnableCesaMagRealVarFunc"
      default_layer_kwargs: 
        parameters:
          norm_per_inv_type: 
            value: layer
          mag_func: 
            value: nick
          output_features:
            value: real
          max_order:
            values: [1, 2, 3, 4]
      drop_rate:
        value: 0.1
      channels_masking:
        value: true 
  model_name:
    value: MBPrototype
  optimizer_hparams:
    parameters:
      lr:
        value: 0.0015
      weight_decay:
        value: 0.05
  optimizer_name:
    value: AdamW
  label_smoothing:
    value: 0.1
  run_name:
    value: learnablecesa-rotmnist-mag-func-min-frequency
  seed:
    values: [42, 7, 123]