d_hparams:
  batch_size: 16
dataset_name: ColorectalHistology
early_stopping: 30
epochs: 150
lr_hparams:
  gamma: 0.1
  milestones:
  - 50
  - 100
  - 125
lr_name: MultiStepLR
model_name: PrototypeOptimalInvCNN
m_param:
  in_channels: 3
  input_size: 150
  n_blocks: 4
  m_layers: 3
  learnable_radial: True
  init_channels: [8, 16, 32, 58]
  filter_size: [15, 11, 11, 11]
optimizer_hparams:
  lr: 0.01525
optimizer_name: AdamW
seed: 223
run_name: prototype-histology-radial-middle