program: scripts/training.py
name: katelyn-compiled
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  dataset_name:
    value: ImageFoldersDataModule
  d_hparams:
    parameters:
      batch_size:
        value: 64
      test_batch_size:
        value: 128
      train_dir:
        value: /home/karella/Projects/rotation-invariant-neural-networks/hippy2d/data/v1_tiles_224x224/train
      valid_dir:
        value: /home/karella/Projects/rotation-invariant-neural-networks/hippy2d/data/v1_tiles_224x224/val
      test_dir:
        value: /home/karella/Projects/rotation-invariant-neural-networks/hippy2d/data/v1_tiles_224x224/test
      target_size:
        value: 224
      aug_gray_scale:
        value: true
      to_complex:
        value: false
  model_name:
    value: MBPrototype
  m_param:
    parameters:
      in_channels:
        value: 1
      input_size:
        value: 224
      disable_act1:
        value: true
      norm1_layer:
        value: none
      norm2_layer:
        value: batch
      kernels_size:
        value: [11, 11, 11]
      layers:
        value: [1, 2, 2]
      channels:
        value: [16, 32, 40]
      block_types:
        value: ["MBConvBlock", "MBConvBlock", "MBConvBlock"]
      layer:
        value: "OptimalBasisBlock"
      channels_masking:
        value: false
      default_layer_kwargs: 
        parameters:
          pre_norm_func:
            value: "layer_norm"
          phase_func:
            value: "polar"
          mag_func:
            value: "nicks"
          max_order:
            value: 3
  optimizer_hparams:
    parameters:
      lr:
        value: 0.0015
      weight_decay:
        value: 0.05
  optimizer_name:
    value: AdamW
  label_smoothing:
    value: 0.1
  run_name:
    value: compiled-katelyn
  seed:
    values: [42, 7, 74]