d_hparams:
  batch_size: 64
  data_dir: data/brandon_data/tomas-dataset-crops
  target_size: 96
  to_complex: false
  use_circ_mask: true
dataset_name: TomasCrops
early_stopping: 30
epochs: 60
label_smoothing: 0.1
lr_hparams:
  gamma: 0.1
  milestones:
  - 15
  - 30
  - 50
lr_name: MultiStepLR
model_name: MBPrototype
m_param:
  in_channels: 1
  num_classes: 5
  input_size: 96
  disable_act1: true
  norm1_layer: layer
  norm2_layer: batch
  kernels_size: [11, 11, 11]
  layers: [2, 3, 3]
  channels: [20, 24, 30]
  block_types: ["MBConvBlock", "MBConvBlock", "MBConvBlock"]
  layer: "LearnableCesaMagRealLayer"
  drop_rate: 0.2
  channels_masking: true
optimizer_hparams:
  lr: 0.001525
  weight_decay: 0.05
optimizer_name: AdamW
run_name: mbconv-tomas-crops-magreal-larger
seed: 42
