d_hparams:
  batch_size: 32
  data_dir: data
  to_complex: true
dataset_name: RESISC45
early_stopping: 15
epochs: 200
lr_hparams:
  gamma: 0.1
  milestones:
  - 10
  - 50
  - 90
lr_name: MultiStepLR
m_param:
  in_channels: 3
  num_classes: 45
  input_size: 256
model_name: ResHNeXtv3
optimizer_hparams:
  lr: 0.001
optimizer_name: AdamW
run_name: resHNeXt-RESISC45
seed: 42
