d_hparams:
  batch_size: 8
dataset_name: ColorectalHistology
early_stopping: 30
epochs: 150
lr_name: CosineAnnealingLR
lr_hparams:
  T_max: 150
model_name: PrototypeOptimalInvCNN
m_param:
  in_channels: 3
  input_size: 150
  n_blocks: 4
  m_layers: 3
  init_channels: [8, 16, 24, 35]
  kernel_size: [15, 11, 11, 11]
  num_classes: 8
  layer: LearnableFlusser
optimizer_hparams:
  lr: 0.01525
optimizer_name: AdamW
seed: 390
run_name: learnable-histology