name: hippy2d
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11.7
  - pip
  - pip: 
    - click==8.2.*
    - torch==2.7.*
    - torchvision==0.22.*
    - loguru==0.7.*
    - GitPython==3.1.*
    - lovely-tensors==0.1.*
    - einops==0.8.*
    - lightning==2.5.*
    - scipy==1.16.*
    - pytest==8.4.*
    - e2cnn==0.2.*
    - tensorboard==2.20.*
    - pandas==2.3.*
    - datasets[vision]
    - ray[tune]==2.48.*
    - scikit-learn==1.7.*
    - timm==1.0.*
    - wandb==0.22.*
    - h5py==3.15.*
    - gdown==5.2.*
