d_hparams:
  batch_size: 16
  data_dir: data
dataset_name: RotMnist
early_stopping: 15
epochs: 100
lr_hparams:
  gamma: 0.95
lr_name: ExponentialLR
model_name: PrototypeTiny
m_param:
  scale_channels: 4
optimizer_hparams:
  lr: 0.01525
  weight_decay: 0.05
optimizer_name: AdamW
seed: 42
run_name: prototype-rotmnist