d_hparams:
  batch_size: 32
dataset_name: ColorectalHistology
early_stopping: 15
epochs: 50
lr_hparams:
  gamma: 0.1
  milestones:
  - 10
  - 15
  - 25
lr_name: MultiStepLR
model_name: PrototypeOptimalInvCNN
m_param:
  in_channels: 3
  input_size: 150
  init_channels: 6
  n_blocks: 4
  m_layers: 3
  filter_size: 11
optimizer_hparams:
  lr: 0.01525
optimizer_name: AdamW
seed: 42
run_name: prototype-histology-smaller