d_hparams:
  batch_size: 32
  data_dir: data
  pad: 0
  to_complex: false
dataset_name: MnistRotTest
early_stopping: 10
epochs: 100
lr_hparams:
  gamma: 0.1
  milestones:
  - 10
  - 50
  - 90
lr_name: MultiStepLR
m_param:
  in_channels: 1
  num_classes: 10
model_name: Resnet18
optimizer_hparams:
  lr: 0.001
optimizer_name: AdamW
run_name: resnet18-baseline
seed: 42