d_hparams:
  batch_size: 32
dataset_name: ColorectalHistology
early_stopping: 15
epochs: 50
lr_hparams:
  gamma: 0.1
  milestones:
  - 10
  - 25
  - 40
m_param:
  pretrained: false
model_name: timm:test_convnext3
optimizer_hparams:
  lr: 0.001
optimizer_name: AdamW
run_name: test_convnext3.r160-histology
seed: 42
