d_hparams:
  batch_size: 32
dataset_name: ColorectalHistology
early_stopping: 15
epochs: 50
lr_hparams:
  gamma: 0.1
  milestones:
  - 10
  - 25
  - 40
m_param:
  num_classes: 7
  pretrained: false
model_name: timm:test_resnet 
optimizer_hparams:
  lr: 0.001
optimizer_name: AdamW
run_name: test_resnet.r160_in1k-histology
seed: 42
