d_hparams:
  batch_size: 8
  normalize: True
  aug_crop: True
  aug_scale: True
  aug_clr_jitter: False
dataset_name: ColorectalHistology
early_stopping: 30
epochs: 150
lr_name: CosineAnnealingLR
lr_hparams:
  T_max: 150
m_param:
  pretrained: false
model_name: timm:test_resnet.r160_in1k 
optimizer_hparams:
  lr: 0.001
optimizer_name: AdamW
run_name: test_resnet-normalize-label-smoothing
seed: 42
