
program: scripts/training.py
name: learnablecesa-mnist-rot-test
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  dataset_name:
    value: MnistRotTest
  d_hparams:
    parameters:
      batch_size:
        value: 32
      test_batch_size:
        value: 128
      data_dir:
        value: data
      pad:
        value: 0
      to_complex:
        value: false
  early_stopping:
    value: 15
  epochs:
    value: 100
  lr_name:
    value: MultiStepLR
  lr_hparams:
    parameters:
      gamma:
        value: 0.1
      milestones:
        value: [10, 50, 90]
  m_param:
    parameters:
      in_channels:
        value: 1
      num_classes:
        value: 10 
      norm:
        value: batch
      kernels_size:
        value: [11, 11, 11]
      layers:
        value: [1, 2, 2]
      channels:
        value: [16, 20, 26]
      block_types:
        value: ["MBConvBlock", "MBConvBlock", "MBConvBlock"]
      layer:
        value: LearnableCesa
      drop_rate:
        value: 0.1
      channels_masking:
        value: true 
  model_name:
    value: Resnet
  optimizer_hparams:
    parameters:
      lr:
        value: 0.001
      weight_decay:
        value: 0.05
  optimizer_name:
    value: AdamW
  label_smoothing:
    value: 0.1
  run_name:
    value: learnablecesa-mnist-rot-test
  seed:
    values: [42, 7, 123, 24, 74]