
program: scripts/training.py
name: resnet18-mnist-rot-test
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  dataset_name:
    value: MnistRotTest
  d_hparams:
    parameters:
      batch_size:
        value: 32
      test_batch_size:
        value: 128
      data_dir:
        value: data
      pad:
        value: 0
      to_complex:
        value: false
  early_stopping:
    value: 15
  epochs:
    value: 100
  lr_name:
    value: MultiStepLR
  lr_hparams:
    parameters:
      gamma:
        value: 0.1
      milestones:
        value: [10, 50, 90]
  m_param:
    parameters:
      in_channels:
        value: 1
      num_classes:
        value: 10 
  model_name:
    value: Resnet18
  optimizer_hparams:
    parameters:
      lr:
        value: 0.001
  optimizer_name:
    value: AdamW
  label_smoothing:
    value: 0.1
  run_name:
    value: resnet18-mnist-rot-test
  seed:
    values: [42, 7, 123, 24, 74]