program: scripts/training.py
name: rotmnist-RIC
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  dataset_name:
    value: RotMnist
  d_hparams:
    parameters:
      batch_size:
        value: 16
      test_batch_size:
        value: 16
      data_dir:
        value: data
      upscale_size:
        value: 64
  early_stopping:
    value: 15
  epochs:
    value: 60
  lr_name:
    value: MultiStepLR
  lr_hparams:
    parameters:
      gamma:
        value: 0.1
      milestones:
        value: [10, 50, 90]
  model_name:
    value: RIC
  m_param:
    parameters:
      in_channels: 
        value: 1
      input_size:
        value: 64
      batch_size:
        value: 16
  optimizer_hparams:
    parameters:
      lr:
        value: 0.001525
      weight_decay:
        value: 0.05
  optimizer_name:
    value: AdamW
  label_smoothing:
    value: 0.1
  run_name:
    value: RIC-rotmnist
  seed:
    values: [42, 43, 44]
